name: build
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'
          channel: stable 
      - name: Build web
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
      - name: Deploy web
        env:
          WEB_DEPLOY_TOKEN: ${{ secrets.WEB_DEPLOY_TOKEN }}
        if: github.ref =='refs/heads/main'
        run: |
          curl -sL https://firebase.tools | bash
          firebase deploy --token $WEB_DEPLOY_TOKEN